# This is a basic workflow to help you get started with Actions

name: Doxygen Action

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]


  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Check out the repository
      uses: actions/checkout@v4
        
    - name: Create clean gh-pages branch
      run:  git checkout -b gh-pages

    - name: Generate autodocs for IPPL
      run:  make -C doc

    - name: Move generated autodocs to target directory
      run:  mv doc/html IPPL-doc

    - name: Add generated autodocs to Git repo in the gh-pages branch
      run:  |
        git config --global user.email "IPPL-github-bot@suse.com"
        git config --global user.name  "$GITHUB_WORKFLOW GitHub action"
        git add IPPL-doc
        git commit -am "Generated IPPL doc"

    - name: Publish autodocs as GitHub pages
      run:  git push -f origin gh-pages:gh-pages

    - name: Result URLs
      run:  |
        REPO_OWNER=$(echo $GITHUB_REPOSITORY | cut -d '/' -f 1)
        REPO_NAME=$(echo $GITHUB_REPOSITORY | cut -d '/' -f 2)
        echo "Formatted IPPL docs:  https://$REPO_OWNER.github.io/$REPO_NAME/IPPL-doc"
        echo ""
        echo "GitHub pages branch: $GITHUB_SERVER_URL/$GITHUB_REPOSITORY/tree/gh-pages" 